name: Deploy React App

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Deploy to VPS
        uses: appleboy/ssh-action@v1.0.0

        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script_stop: true

          script: |
            cd /root

            if [ ! -d "Contact-Us-Page" ]; then
              git clone https://github.com/Mehak-Jain913/Contact-Us-Page.git
            fi

            cd /root/Contact-Us-Page

            git pull origin main
            npm install
            npm run build

            rm -rf /var/www/html/*
            cp -r dist/* /var/www/html/

            systemctl restart nginx